kind = "DojoContract"
class_hash = "0xe69574d33ece81e95331047916d91478efa2a1594b5ade5925467c1209bf33"
original_class_hash = "0xe69574d33ece81e95331047916d91478efa2a1594b5ade5925467c1209bf33"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
